#!/bin/bash 

############################################################################# 
# Source files
#############################################################################

#source ~/.bash_profile
source includes/config

############################################################################# 
# Check usage
#############################################################################

#Usage check
: ${1?"Usage: $0 SITE"}

#Check local status
loc_status=$(drush @$1 status|grep "Drupal bootstrap"|awk '{ print $4 }')

if [ "$loc_status" != "Successful" ]; then
	echo site $1 not found.
	exit
fi


#drupal directory
dd=$(drush @$1 dd)
db_folder=$dd/../db

#Check folder db exist
if [ ! -d $db_folder ]; then
	mkdir $db_folder
fi

drush @$1 sql-dump --result-file=$db_folder/$1.sql

rm -f $db_folder/$1.sql.bz2

bzip2 $db_folder/$1.sql