#!/bin/bash

############################################################################# 
# Source files
#############################################################################

source ~/.bash_profile
source includes/config
source includes/functions

############################################################################# 
# Check usage and platform settings
#############################################################################

#Usage check
: ${1?"Usage: $0 SITE"}


# Mysql login
read -s -p "Enter mysql root password: " rootpass

#Test mysql connection
while ! mysql -u root -p$rootpass  -e ";" ; do
       read -s -p "Can't connect, please retry: " rootpass
done

echo "";


# Pass all tests


#Remove db
mysqladmin -uroot -p$rootpass -f DROP $1_db;
echo $1_db deleted

#Remove user
mysql -uroot -p$rootpass -e "DROP USER $1_user@localhost;";
echo User $1_user is removed.

#remove vhost file
sudo rm -f $APACHEDIR/other/$1.$SERVER.conf
echo Remove vhost alias: $APACHEDIR/other/$1.$SERVER.conf

#remove drush alias
rm -f /Users/$USER/.drush/$1.aliases.drushrc.php
echo Remove drush alias: /Users/$USER/.drush/$1.aliases.drushrc.php

#remove site directory
sudo rm -rf $WWW/$1
echo Remove site directory.

#remove host alias
sed "/$1.$SERVER/d" /etc/hosts > tmp
sudo mv tmp /etc/hosts
rm -f tmp
echo Updated etc/hosts.

#apache restart
sudo apachectl restart
echo apache restarted.