#!/bin/bash

############################################################################# 
# Source files
#############################################################################

source ~/.bash_profile
source includes/config
source includes/functions

############################################################################# 
# Check usage and platform settings
#############################################################################

#Usage check
: ${1?"Usage: $0 SITE"}


# Mysql login
read -s -p "Enter mysql root password: " rootpass

#Test mysql connection
while ! mysql -u root -p$rootpass  -e ";" ; do
       read -s -p "Can't connect, please retry: " rootpass
done

echo "";


# Pass all tests


#Remove db
mysqladmin -uroot -p$rootpass -f DROP $1_db;
echo $1_db deleted

#Remove user
mysql -uroot -p$rootpass -e "DROP USER $dbuser@localhost;";
echo User $dbuser is removed.

#remove vhost file
sudo rm -f $APACHEDIR/other/$code.$SERVER.conf
echo Remove vhost alias: $APACHEDIR/other/$code.$SERVER.conf

#remove drush alias
rm -f /Users/$USER/.drush/$code.aliases.drushrc.php
echo Remove drush alias: /Users/$USER/.drush/$code.aliases.drushrc.php

#remove site directory
rm -rf $WWW/$1

#apache restart
sudo apachectl restart
echo apache restarted.