#!/bin/bash 

############################################################################# 
# Source files
#############################################################################

source ~/.bash_profile
source includes/config
source includes/functions

############################################################################# 
# Check usage
#############################################################################

#Usage check
: ${1?"Usage: $0 SITE [live | dev]"}

./startup $1


#Check remote status
status=$(drush @$1.$2 status|grep "Drupal bootstrap"|awk '{ print $4 }')
if [ "$status" != "Successful" ]; then
	echo Drupal site found on @$1.$2, please use drush command instead.
	exit
fi
