#!/bin/bash 

############################################################################# 
# Source files
#############################################################################

source ~/.bash_profile
source includes/config
source includes/functions

############################################################################# 
# Check usage
#############################################################################

#Usage check
: ${2?"Usage: $0 SITE [live | dev]"}

#Check lcoal status
#loc_status=$(drush @$1 status|grep "Drupal bootstrap"|awk '{ print $4 }')

#if [ "$loc_status" = "Successful" ]; then
#	echo Drupal site $1 is already existed, please use drush commands instead.
#	exit
#fi

############################################################################# 
# Server info
#############################################################################

read -p "What is the actual domain of the website: " domain

############################################################################# 
# Check settings
#############################################################################


#Check vhost exist
if [ -f $APACHEDIR/other/$1.$SERVER.conf ]; then
  echo vhost $1.$SERVER is already existed
  exit
fi

#Check project directory exist
if [ -d $WWW/$1 ]; then
  echo Folder $1 is already existed
  exit
fi

#Check drush settings
if [ ! -d /Users/$USER/.drush ]; then
	echo ".drush folder not found"
	exit
fi

#Check db exist

read -s -p "Enter mysql root password: " rootpass

#Test mysql connection
while ! mysql -u root -p$rootpass  -e ";" ; do
       read -s -p "Can't connect, please retry: " rootpass
done
echo "";

check_db_exist $1_db $rootpass
db_exist=$?

if [ $db_exist = 1 ]; then	
	echo database $1_db alread exist
	exit
fi

#Check remote status
status=$(drush @$1.$2 status|grep "Drupal bootstrap"|awk '{ print $4 }')
if [ "$status" != "Successful" ]; then
	echo @$1.$2 cannot be detected. Remove $1.localhost now

	./destroy $1

	exit
fi


drush rsync --delete @$1.$2 @$1 -y 

drush sql-sync @$1.$2 @$1 --no-cache -y

chmod 755 $WWW/$1