#!/bin/bash 

############################################################################# 
# Source files
#############################################################################

source ~/.bash_profile
source includes/config
source includes/functions


############################################################################# 
# Check usage
#############################################################################

#Usage check
: ${1?"Usage: $0 SITE"}

cd $(drush @$1 dd)

if [ -n "$2" ] && [ "$2" = "dev" ]; then
	git co master
	
	git pull kw
	
else 
	git pull in
fi

drush @$1 updb -y