#!/bin/bash 

############################################################################# 
# Source files
#############################################################################

source ~/.bash_profile
source includes/config
source includes/functions


############################################################################# 
# Check usage
#############################################################################

#Usage check
: ${1?"Usage: $0 SITE"}

cd $(drush @$1 dd)

if [ -n "$2" ] then
	git co $2
	
	git pull kw $2
	
else 
	git pull in
fi

drush @$1 updb -y