#!/bin/bash


############################################################################# 
# loc2dev = local to dev
# Require: local exist
# Actions: replace code, file, db (no cache)
############################################################################# 

#############################################################################
# Source files
#############################################################################

source ~/.bash_profile
source includes/config
source includes/functions

############################################################################# 
# Check usage and platform settings
#############################################################################

#Usage check
: ${1?"Usage: $0 SITE"}

#Check local exist
loc_status=$(drush @$1 status|grep "Drupal bootstrap"|awk '{ print $4 }')


if [ "$loc_status" = "Successful" ]; then
	
	#deal with settings.php
	sudo mv -f $WWW/$1/sites/default/settings.php $WWW/$1/sites/default/settings.local 
	sudo mv -f $WWW/$1/sites/default/settings.dev $WWW/$1/sites/default/settings.php
	
	#replace code (with configure)
	drush -v rsync --delete --include-conf @$1 @$1.dev -y 

	#reset settings.php	
	sudo mv -f $WWW/$1/sites/default/settings.php $WWW/$1/sites/default/settings.dev
	sudo mv -f $WWW/$1/sites/default/settings.local $WWW/$1/sites/default/settings.php

	#replace db	
	drush @$1.dev sql-drop -y	
	drush sql-sync @$1 @$1.dev --no-cache -y
	
	#make sure it is in maintenance mode
	drush @$1.dev vset --always-set maintenance_mode 1
	
	drush @$1.dev cc all	
	
	
fi