#!/bin/bash

source ~/.bash_profile

#Usage check
: ${1?"Usage: $0 SITE"}

source includes/config

#Check vhost exist
if [ -f $APACHEDIR/other/$1.$SERVER.conf ]; then
  echo vhost $1.$SERVER is already existed
  exit
fi


#Check site directory exist
if [ -d $WWW/$MSITES/sites/$1.$SERVER ]; then
  echo site $1.localhost is already existed
#  exit
fi

#Check drush settings
if [ ! -d /Users/$USER/.drush ]; then
	echo ".drush folder not found"
	exit
fi

######## Pass all tests ########

#default to msites
if [ -z "$2" ]; then 
	MSITES=msites
else
	MSITES=$2
fi

function check_db_exist {
	DBS=`mysql -uroot -p$rootpass -Bse 'show databases'| egrep -v 'information_schema|mysql'`
	for db in $DBS; do
		if [ "$db" = $1 ]; then
		    echo 1
			return
		fi
	done

	echo 0

}

#Add vhost
 echo "<VirtualHost *:80>
    DocumentRoot $WWW/$MSITES
    ServerName $1.localhost
    <Directory $WWW/$MSITES>
        AllowOverride All
    </Directory>
</VirtualHost>
" | sudo tee -a $APACHEDIR/other/$1.$SERVER.conf

sudo apachectl restart

#Add host alias
if [ ! $(grep -q "$1.$SERVER" /etc/hosts) ]; then
  echo -e "127.0.0.1	$1.$SERVER" | sudo tee -a /etc/hosts
fi


#Add drush alias
echo "<?php
\$aliases['$1'] = array(
    'uri' => '$1.$SERVER',
    'root' => '$WWW/$MSITES',
  );" > /Users/$USER/.drush/$1.aliases.drushrc.php 


#Create site folder
cp -pRva $WWW/$MSITES/sites/default $WWW/$MSITES/sites/$1.$SERVER

#Create Database
read -s -p "Enter mysql root password: " rootpass

#Test mysql connection
while ! mysql -u root -p$rootpass  -e ";" ; do
       read -s -p "Can't connect, please retry: " rootpass
done

echo "";

#Setup variables required
rand=$RANDOM

dbname=$1_db
dbuser=$1_user
dbpass=$(perl -e 'print crypt($ARGV[0], "password")' $rand | sed 's/\///g')
drupaluser='Site Admin'

#Check if db exists
n=1
while [ `check_db_exist $dbname` = 1 ]; do
	dbname=$1_db$n
	dbuser=$1_user$n
	let n+=1
done

#CREATE DB
mysqladmin -uroot -p$rootpass create $dbname;
echo "Database $dbname created, $dbpass"

#CREATE USER
Q1="GRANT USAGE ON * . * TO  '$dbuser'@'localhost' IDENTIFIED BY  '$dbpass';" 
Q2="GRANT ALL PRIVILEGES ON $dbname.* TO '$dbuser'@'localhost' IDENTIFIED BY '$dbpass';"
SQL="${Q1}${Q2}"

mysql -uroot -p$rootpass -e "$SQL"

#Optional settings for manual druapl install
#mkdir $WWW/$MSITES/sites/$1.$SERVER/files
#chmod 777 $WWW/$MSITES/sites/$1.$SERVER/files
#cp $WWW/$MSITES/sites/$1.$SERVER/default.settings.php $WWW/$MSITES/sites/$1.$SERVER/settings.php
#chmod 777 $WWW/$MSITES/sites/$1.$SERVER/settings.php

#INSTALL DRUPAL
drush @$1 site-install ip --db-url=mysql://$dbuser:"$dbpass"@localhost/$dbname --account-name="$drupaluser" --account-pass=$dbpass  --sites-subdir=$1.$SERVER -y

#Check if Drupal install successfully
status=$(drush @$1 status|grep "Drupal bootstrap"|awk '{ print $4 }')

if [ "$status" = "Successful" ]; then	
	
	#drupal directory
	dd=$(drush @$1 dd)

	#Make files directory writable
	chmod -R 777 `drush @$1 dd files`
	chmod 755 $dd/sites/$1.$SERVER
	
	#Enable ipdeploy
	#drush @$1 en ipdeploy --yes

	#Make everthing in files directory writable
	chmod -R 777 `drush @$1 dd files`

	drush @$1 cron
else
	echo Drupal fail to install.
	exit
fi


#Report
echo "Database created: $dbname"
echo "Drupal was installed successfully: "
drush @$1 user-login;