#!/bin/bash 

############################################################################# 
# Source files
#############################################################################

source ~/.bash_profile
source includes/config
source includes/functions


############################################################################# 
# Check usage
#############################################################################

#Usage check
: ${2?"Usage: $0 SITE [live | dev]"}

#Check local status
loc_status=$(drush @$1 status|grep "Drupal bootstrap"|awk '{ print $4 }')

if [ "$loc_status" != "Successful" ]; then
	echo @$1 cannot be detected.
	exit
fi

#Check remote status
status=$(drush @$1.$2 status|grep "Drupal bootstrap"|awk '{ print $4 }')
if [ "$status" != "Successful" ]; then
	echo @$1.$2 cannot be detected.
	exit
fi




drush sql-sync @$1.$2 @$1 -y

drush rsync @tchair.live:%files @tchair:%files -y

drush @tchair cc all

Enable devel modules