#!/bin/bash

############################################################################# 
# Reset (local/dev) = live to local / live to dev
# Require: live exist
# Actions: replace code, file, db
############################################################################# 

#############################################################################
# Source files
#############################################################################

source ~/.bash_profile
source includes/config
source includes/functions

############################################################################# 
# Check usage and platform settings
#############################################################################

#Usage check
: ${1?"Usage: $0 SITE"}

#Cannot reset live site
if [ $(echo $1 | grep ".live") ]; then
	echo 'Cannot reset live site'
	exit
fi


code=$(echo ${1%%.*})
plt=$(echo ${1#*.})

#Make sure the live site exist
status=$(drush @$code.live status|grep "Drupal bootstrap"|awk '{ print $4 }')
if [ "$status" != "Successful" ]; then
	echo 'Error: cannot detect live site'
	exit
fi

	
#replace db
drush @$1 sql-drop -y
drush sql-sync @$code.live @$1 -y
	
############################################################################# 
# Reset dev
#############################################################################
if [ "$plt" = "dev" ]; then
	
	if [ ! -d $WWW/tmp ]; then
		mkdir $WWW/tmp
	fi
		
	#replace code
	drush -v rsync --delete --include-conf @$code.live $WWW/tmp -y 
	
	mv -f $WWW/tmp/sites/default/settings.php $WWW/tmp/sites/default/settings.live 
	mv -f $WWW/tmp/sites/default/settings.dev $WWW/tmp/sites/default/settings.php	
	
	drush -v rsync --delete --include-conf $WWW/tmp/ @$1 -y 
		
	#make sure it is in maintenance mode
	drush @$1 vset --always-set maintenance_mode 1	
	
############################################################################# 
# Reset local
#############################################################################	
else
	#replace code
	drush -v rsync --delete --include-conf @$code.live @$1 -y 
	mv -f $WWW/$code/sites/default/settings.php $WWW/$code/sites/default/settings.live 
	mv -f $WWW/$code/sites/default/settings.local $WWW/$code/sites/default/settings.php
		
fi

drush @$1 cc all	
	

