#!/bin/bash

############################################################################# 
# Source files
#############################################################################

source ~/.bash_profile
source includes/config
source includes/functions

############################################################################# 
# Check usage and platform settings
#############################################################################

#Usage check
: ${1?"Usage: $0 SITE"}

#Check vhost exist
if [ -f $APACHEDIR/other/$1.$SERVER.conf ]; then
  echo vhost $1.$SERVER is already existed
  exit
fi

#Check project directory exist
if [ -d $WWW/$1 ]; then
  echo Folder $1 is already existed
#  exit
fi

#Check drush settings
if [ ! -d /Users/$USER/.drush ]; then
	echo ".drush folder not found"
	exit
fi

############################################################################# 
# Server info
#############################################################################

read -p "What is the actual domain of the website: " domain

############################################################################# 
# Setup vhost, host alias & drush alias
#############################################################################

#Add vhost
 echo "<VirtualHost *:80>
    DocumentRoot $WWW/$1 
    ServerName $1.localhost
    <Directory $WWW/$1>
        AllowOverride All
    </Directory>
</VirtualHost>
" | sudo tee -a $APACHEDIR/other/$1.$SERVER.conf

sudo apachectl restart

#Add host alias
if [ ! $(grep -q "$1.$SERVER" /etc/hosts) ]; then
  echo -e "127.0.0.1	$1.$SERVER" | sudo tee -a /etc/hosts
fi

#Add drush alias
echo "<?php
\$aliases['$1'] = array(
    'uri' => '$1.$SERVER',
    'root' => '$WWW/$1',
  );

\$aliases['$1.dev'] = array(
    'uri' => 'dev.$domain',
	'root' => '/home/$1/dev',
	'ssh-options' => '-p 222',
    'remote-host' => 'dev.$domain',
	'remote-user' => '$1',
	'path-aliases' => array(
		'%dump-dir' => '/home/$1/sql_dump',
     ),
  );

\$aliases['$1.live'] = array(
    'uri' => '$domain',
	'root' => '/home/$1/www',
	'ssh-options' => '-p 222',
    'remote-host' => '$domain',
	'remote-user' => '$1',
	'path-aliases' => array(
		'%dump-dir' => '/home/$1/sql_dump',
     ),
  );

" > /Users/$USER/.drush/$1.aliases.drushrc.php 


############################################################################# 
# Live to local (files only)
#############################################################################

#Check live exist
liv_status=$(drush @$1.live status|grep "Drupal bootstrap"|awk '{ print $4 }')

if [ "$liv_status" = "Successful" ]; then
	
	#replace code (with configure)
	drush -v rsync --delete --include-conf @$1.live @$1 -y 

	#deal with settings.php
	sudo mv -f $WWW/$1/sites/default/settings.php $WWW/$1/sites/default/settings.live
	sudo mv -f $WWW/$1/sites/default/settings.local $WWW/$1/sites/default/settings.php
else
	#live site not exist
	echo @$1.live not exist

	#remove vhost file
	sudo rm -f $APACHEDIR/other/$1.$SERVER.conf
	echo vhost removed.
	
	#remove host alias
	sed "/$1.$SERVER/d" /etc/hosts > tmp/hosts
	sudo mv tmp/hosts /etc/hosts
	echo host alias removed.
	
	#remove drush alias
	rm -f /Users/$USER/.drush/$1.aliases.drushrc.php
	echo drush alias removed.	

	#restart apache
	sudo apachectl restart
	echo apache restarted.

	exit
fi

############################################################################# 
# Create database & user
#############################################################################

read -s -p "Enter mysql root password: " rootpass

#Test mysql connection
while ! mysql -u root -p$rootpass  -e ";" ; do
       read -s -p "Can't connect, please retry: " rootpass
done

echo "";

#Read db info from settings.php
dbname=$(sudo cat $WWW/$1/sites/default/settings.php|grep "^      'database'"|awk '{ print $3 }'| tr -d "'" | tr -d ",")
dbuser=$(sudo cat $WWW/$1/sites/default/settings.php|grep "^      'username'"|awk '{ print $3 }'| tr -d "'" | tr -d ",")
dbpass=$(sudo cat $WWW/$1/sites/default/settings.php|grep "^      'password'"|awk '{ print $3 }'| tr -d "'" | tr -d ",")

#CREATE DB
mysqladmin -uroot -p$rootpass create $dbname;
echo "Database $dbname created, $dbpass"

#CREATE USER
Q1="GRANT USAGE ON * . * TO  '$dbuser'@'localhost' IDENTIFIED BY  '$dbpass';" 
Q2="GRANT ALL PRIVILEGES ON $dbname.* TO '$dbuser'@'localhost' IDENTIFIED BY '$dbpass';"
SQL="${Q1}${Q2}"

mysql -uroot -p$rootpass -e "$SQL"
