#!/bin/bash 

############################################################################# 
# Source files
#############################################################################

source ~/.bash_profile
source includes/config
source includes/functions


############################################################################# 
# Check usage
#############################################################################

#Usage check
: ${1?"Usage: $0 SITE"}

#Check lcoal status
loc_status=$(drush @$1 status|grep "Drupal bootstrap"|awk '{ print $4 }')


if [ "$loc_status" != "Successful" ]; then
	echo site $1 not found.
	exit
fi

#Check remote status
status=$(drush @$1.$2 status|grep "Drupal bootstrap"|awk '{ print $4 }')
if [ "$status" != "Successful" ]; then
	echo Drupal site not found on @$1.$2, please use ./upload instead.
	exit
fi