#!/bin/bash 

############################################################################# 
# Source files
#############################################################################

source ~/.bash_profile
source includes/config
source includes/functions


############################################################################# 
# Check usage and platform settings
#############################################################################

#Usage check
: ${1?"Usage: $0 SITE"}


# Push Workspace to in repository
if [ $1 = pushws ]; then
	
	#Usage check
	: ${2?"Usage: $0 $1 version number"}
	
	pushws $2
	
	exit
fi

#Check vhost exist
if [ -f $APACHEDIR/other/$1.$SERVER.conf ]; then
  echo vhost $1.$SERVER is already existed
  exit
fi

#Check project directory exist
if [ -d $WWW/$1 ]; then
  echo Folder $1 is already existed
  exit
fi

#Check drush settings
if [ ! -d /Users/$USER/.drush ]; then
	echo ".drush folder not found"
	exit
fi

#Check db exist
if [ check_db_exist $1_db ]; then	
	echo database $1_db alread exist
	exit
fi

#####

############################################################################# 
# Copy ip from ipcache
#############################################################################

branch=$PRESET_BRANCH

#in repos
repo=${REPOS[0]}

printf "%s = %s\n" 'Repo' $repo
printf "%s = %s\n" 'Branch' $branch

#if ipcache not exist, clone from github
if [ ! -d $WWW/ipcache ]; then
	echo Clone $branch branch
	git clone --branch $branch $repo $WWW/ipcache	
	
else

	cd $WWW/ipcache
	git co $branch
	git pull

fi

if if [ -z "$2" ]; then; if [ $2 = dev ]; then
	echo dev
	#kw repos
	repo=${REPOS[1]}
		
	cd $WWW/ipcache
	git remote add kw $repo
	git pull kw
	git co -b master kw/master
	
	git co master
	git pull kw	
fi; fi

cd $WWW/ipcache
git branch


