#!/bin/bash 

############################################################################# 
# Source files
#############################################################################

source ~/.bash_profile
source includes/config
source includes/functions

THEME='omega'

############################################################################# 
# Get Opts
#############################################################################
usage()
{
cat << EOF
usage: $0 options SITE

OPTIONS:
   -h      Show this message.
   -t      Define a parent theme, default to omega if not specify.
EOF
}
while getopts ":hp" opt; do
  case $opt in

  	h)
		usage
		exit 1
	;;
	
    t)
		THEME=$OPTARG
		shift $((OPTIND-1))
	;;
			
    \?)
		echo "Invalid option: -$OPTARG" >&2
		exit 1
	;;
  esac
done


############################################################################# 
# Check usage
#############################################################################

#Usage check
: ${1?"Usage: $0 SITE"}


dd=$(drush @$1 dd)

if [ $THEME == 'omega' ]; then		
	#1. Enable omega_tools
	drush @$1 pm-enable omega_tools -y
	
	#2. Create new sub theme
	drush @$1 ipconfig_create_theme $1	

	#3. Settings for SCSS
	#copy config.rb
	cp $dd/profiles/ip/themes/zen/STARTERKIT/config.rb $dd/sites/default/themes/$1/


	mv $dd/sites/default/themes/$1/css $dd/sites/default/themes/$1/sass

	#mv *.css to *.scss
	mv $dd/sites/default/themes/$1/sass/global.css $dd/sites/default/themes/$1/sass/global.scss	
	mv $dd/sites/default/themes/$1/sass/$1-alpha-default-narrow.css $dd/sites/default/themes/$1/sass/$1-alpha-default-narrow.scss
	mv $dd/sites/default/themes/$1/sass/$1-alpha-default-normal.css $dd/sites/default/themes/$1/sass/$1-alpha-default-normal.scss
	mv $dd/sites/default/themes/$1/sass/$1-alpha-default-wide.css $dd/sites/default/themes/$1/sass/$1-alpha-default-wide.scss
	mv $dd/sites/default/themes/$1/sass/$1-alpha-default.css $dd/sites/default/themes/$1/sass/$1-alpha-default.scss

	mkdir $dd/sites/default/themes/$1/css


	#4. Pre-defined styles
	#_variables.scss
	cp $dd/profiles/ip/themes/theme_settings/_variables.scss $dd/sites/default/themes/$1/sass/

	# add scaffold.scss
	cat $dd/profiles/ip/themes/theme_settings/global.scss >> $dd/sites/default/themes/$1/sass/global.scss
	cat $dd/profiles/ip/themes/theme_settings/scaffold.scss >> $dd/sites/default/themes/$1/sass/$1-alpha-default-narrow.scss
	cat $dd/profiles/ip/themes/theme_settings/scaffold.scss >> $dd/sites/default/themes/$1/sass/$1-alpha-default-normal.scss
	cat $dd/profiles/ip/themes/theme_settings/scaffold.scss >> $dd/sites/default/themes/$1/sass/$1-alpha-default-wide.scss
	cat $dd/profiles/ip/themes/theme_settings/scaffold.scss >> $dd/sites/default/themes/$1/sass/$1-alpha-default.scss
	
	#5. Replace the log and site_name variable with delta blocks
	
	#theme settings: disable variable logo and site_name 
	
	cat $dd/profiles/ip/themes/theme_settings/info_settings.txt >> $dd/sites/default/themes/$1/$1.info
	
	drush @$1 cc all
	
	#enable in_site_block module: 
	drush @$1 ipconfig_enable_site_blocks
	
	#6. Run compass watch at the end. (script is located at the bottom of the file)
	cd $dd/sites/default/themes/$1
	compass watch
fi