#!/bin/bash 

while getopts ":a" opt; do
  case $opt in
    a)
      echo "-a was triggered!" >&2
		shift $((OPTIND-1))
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
		shift $((OPTIND-1))
      ;;
  esac
done

############################################################################# 
# Check usage
#############################################################################

#Usage check
: ${1?"Usage: $0 SITE"}

echo $1