#!/bin/bash 

while getopts ":a" opt; do
  case $opt in
    a)
      echo "-a was triggered!" >&2
		shift $((OPTIND-1))
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
		shift $((OPTIND-1))
      ;;
  esac
done

echo $1