#!/bin/bash

#Usage check
: ${1?"Usage: $0 SITE"}

source includes/*
source includes/update_3

#check site exist
dd=$(drush @$1 dd)

if [ -d "$dd" ]; then
  let current_version=$(cat $dd/version|grep "update-schema"|awk '{ print $2 }')
else
  echo Site $1 not found
  exit
fi

echo "Checking updates..."
cd IP
silent=$(git pull)

if [ $2 = "test" ]; then
  silent=$(git co test)
else
  silent=$(git co stage)
fi

let latest_version=$(cat version|grep "update-schema"|awk '{ print $2 }')

if [ $current_version = $latest_version ]; then
  echo Site $1 is up to date.
  exit
fi


# Pass all tests

# Do all require updates
let c=current_version
while [  $c -lt $latest_version ]; do
  update_$((c+1)) $1
  let c=c+1 
done

#update version
cp -f version $dd
echo Update succeed 