#!/bin/bash 

############################################################################# 
# Source files
#############################################################################

source ~/.bash_profile
source includes/config
source includes/functions

############################################################################# 
# Check usage
#############################################################################

#Usage check
: ${1?"Usage: $0 SITE [live | dev]"}

#Check remote status
status=$(drush @$1.$2 status|grep "Drupal bootstrap"|awk '{ print $4 }')

if [ "$loc_status" = "Successful" ]; then
	echo Successful
else
	echo fail
fi

#if [ $2 = live ]; then 
#	drush rsync --include-conf @$1 @$1.$2 -y 
#	drush 
#fi