#!/bin/bash 

############################################################################# 
# Source files
#############################################################################

source ~/.bash_profile
source includes/config
source includes/functions

############################################################################# 
# Check usage
#############################################################################

#Usage check
: ${1?"Usage: $0 SITE [live | dev]"}

#Check remote status
status=$(drush @$1.$2 status|grep "Drupal bootstrap"|awk '{ print $4 }')

if [ "$loc_status" = "Successful" ]; then
	echo drupal site found on @$1.$2, please use drush command instead.
	
	exit
fi

if [ $2 = dev ]; then 
	echo dev
fi

drush rsync --include-conf @$1 @$1.$2 -y 
drush 
