#!/bin/bash

function check_db_exist {
	DBS=`mysql -uroot -p$rootpass -Bse 'show databases'| egrep -v 'information_schema|mysql'`
	for db in $DBS; do
		if [ "$db" = $1 ]; then
			return $TRUE
		fi
	done


}


#push workspace
function pushws {
	
	git co kelvin
	
	git push kw kelvin

	git co master
	git pull in master
	
	git merge kelvin
	
	git reset in/master
	
	git add .
	git add -u
	
	git commit
	
	git tag -a $1 -m 'version $1'
	
	git push in master
	
	git push --tags in
	
	git co kelvin
} 

#push ip
function puship {
	
	
	#Check project directory exist
	if [ ! -d $WWW/$1 ]; then
	  echo Folder $1 is not existed
	  exit
	fi
	
	cd $WWW/$1
	
	git co master
	

}